#!/bin/sh
export XDG_CURRENT_DESKTOP="bspwm"

###--- Autostart ---###
# Peripheral setup
sxhkd &
wmname LG3D

# Multi-monitor setup
INTERNAL_INTEL="eDP-1"
INTERNAL_NVIDIA="eDP-1-1"
EXTERNAL="HDMI-0"

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

if xrandr | grep "$EXTERNAL connected"; then
    xrandr --output DP-0 --off \
        --output DP-1 --off \
        --output $EXTERNAL --mode 2560x1440 --pos 0x0 --rotate normal \
        --output $INTERNAL_NVIDIA --mode 1920x1080 --pos 2560x360 --rotate normal
    bspc monitor $EXTERNAL -d 1 2 3 4 5
    bspc monitor $INTERNAL_NVIDIA -d 6 7 8 9 10
elif xrandr | grep "$INTERNAL_NVIDIA connected"; then
    xrandr --output DP-0 --off \
        --output DP-1 --off \
        --output $EXTERNAL --off \
        --output $INTERNAL_NVIDIA --mode 1920x1080 --pos 0x0 --rotate normal
    bspc monitor $INTERNAL_NVIDIA -d 1 2 3 4 5 6 7 8 9 10
elif xrandr | grep "$INTERNAL_INTEL connected"; then
    bspc monitor $INTERNAL_INTEL -d 1 2 3 4 5 6 7 8 9 10
fi

# Background apps
nm-applet &
blueman-applet &
compton &
#birdtray &
dunst &
optimus-manager-qt &
$HOME/.config/polybar/launch.sh &
$HOME/.config/scripts/setup_peripherals.sh

# Aesthetics
xrdb -load ~/.Xdefaults &
feh --bg-fill ~/.config/wallpaper.png &

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52

bspc config focus_follows_pointer false
bspc config borderless_monocle    true
bspc config gapless_monocle       true

#https://www.reddit.com/r/bspwm/comments/85hr4c/making_a_scratchpaddropdown_terminal_in_bspwm/
#TODO fix $HOME/.config/scripts/launch_scratchpad.sh &
bspc rule -a URxvt:scratchpad sticky=on state=floating hidden=on
bspc rule -a Zathura          state=tiled
bspc rule -a Skype state=floating

# 2 - Big programs
bspc rule -a jetbrains-idea desktop='^2'
bspc rule -a jetbrains-studio desktop='^2'
bspc rule -a jetbrains-pycharm desktop='^2'
bspc rule -a jetbrains-clion desktop='^2'
bspc rule -a jetbrains-clion desktop='^2'
bspc rule -a rstudio desktop='^2'
bspc rule -a Emulator desktop='^2'
bspc rule -a resolve desktop='^2'

# 3 - Complementary to work
bspc rule -a Gitkraken desktop='^3'
bspc rule -a Zotero desktop='^3'

# 5 - Media manipulation
bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Inkscape desktop='^5'
bspc rule -a Audacity desktop='^9'

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# 6 - Games
bspc rule -a TLauncher desktop='^6'
bspc rule -a Minecraft desktop='^6'
bspc rule -a Steam desktop='^6'
# 8 - Music
bspc rule -a Spotify desktop='^8'
# 9 - Email/Calendar
bspc rule -a Thunderbird desktop='^9'
# 10 - Comms
bspc rule -a discord desktop='^10'
bspc rule -a slack desktop='^10'
bspc rule -a "microsoft teams - preview" desktop='^10'

/usr/lib/polkit-kde-authentication-agent-1

set -l bspwm_root_id (xdo id -N Bspwm -n root | sort | head -n 1)
for wid in (xdotool search --class plasmashell); do
    bspc config bottom_padding 35
done
