#! /bin/sh

###--- Autostart ---###
# Peripheral setup
sxhkd &
#setxkbmap us ,mode "default" &
xmodmap ~/.config/scripts/mykeyboard.xmodmap &
#easystroke &
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" "1" &
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" "1" &
xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Natural Scrolling Enabled" "0" &

# Background apps
nm-applet &
blueman-applet &
#start-pulseaudio-x11 &
compton &
dunst &

# Aesthetics
xrdb -load ~/.Xdefaults &
feh --bg-fill ~/.config/wallpaper.png &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52

bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a '*:zathura'         state=tiled

# 5 - Media manipulation
bspc rule -a Gimp desktop='^5' state=floating follow=on
# 5 - Media manipulation
bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Inkscape desktop='^5'
bspc rule -a Audacity desktop='^9'

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# 6 - Games
bspc rule -a TLauncher desktop='^6'
bspc rule -a Minecraft desktop='^6'
bspc rule -a Steam desktop='^6'
# 10 - Comms
bspc rule -a discord desktop='^10'

#https://www.reddit.com/r/bspwm/comments/85hr4c/making_a_scratchpaddropdown_terminal_in_bspwm/
bspc rule -a URxvt:scratchpad sticky=on state=floating hidden=on
urxvt -name scratchpad -e ~/.config/scripts/scratchpad.sh &
$HOME/.config/polybar/launch.sh

set -l bspwm_root_id (xdo id -N Bspwm -n root | sort | head -n 1)
for wid in (xdotool search --class plasmashell)
    bspc config bottom_padding 35
end
